name: Build Docker Image

on:
  push:
    branches:
      - main  # or replace 'main' with your default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t otokindle .
